name: wasedatime
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  sqflite: ^2.2.8+4
  path: ^1.8.3
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
      - asset: fonts/Inter-Regular.ttf
      - asset: fonts/Inter-SemiBold.ttf
        weight: 600
    - family: Segoe UI
      fonts:
      - asset: fonts/segoeui-Regular.ttf
      - asset: fonts/segoeui-SemiBold.ttf
        weight: 600
  uses-material-design: true
