class Course {
  final String id;
  final String title;
  final String classroom;

  Course({required this.id, required this.title, required this.classroom});
}

enum Periods {
  mon1,
  mon2,
  mon3,
  mon4,
  mon5,
  mon6,
  tue1,
  tue2,
  tue3,
  tue4,
  tue5,
  tue6,
  wed1,
  wed2,
  wed3,
  wed4,
  wed5,
  wed6,
  thu1,
  thu2,
  thu3,
  thu4,
  thu5,
  thu6,
  fri1,
  fri2,
  fri3,
  fri4,
  fri5,
  fri6,
  sat1,
  sat2,
  sat3,
  sat4,
  sat5,
  sat6
}

final Map<Periods, dynamic> classes = {
  Periods.mon1: Course(id: "1", title: "Statistics", classroom: "61-103"),
  Periods.mon2: Course(id: "1", title: "Statistics", classroom: "61-103"),
  Periods.mon3: Course(id: "1", title: "Statistics", classroom: "61-103"),
  Periods.mon4: Course(id: "1", title: "Statistics", classroom: "61-103"),
  Periods.mon5: Course(id: "1", title: "Statistics", classroom: "61-103"),
  Periods.tue1: Course(id: "1", title: "Statistics", classroom: "61-103"),
  Periods.tue2: Course(id: "1", title: "Statistics", classroom: "61-103"),
  Periods.tue3: null,
  Periods.tue4: null,
  Periods.tue5: null,
  Periods.tue6: null,
  Periods.wed1: null,
  Periods.wed2: null,
  Periods.wed3: null,
  Periods.wed4: null,
  Periods.wed5: null,
  Periods.wed6: null,
  Periods.thu1: null,
  Periods.thu2: null,
  Periods.thu3: null,
  Periods.thu4: null,
  Periods.thu5: null,
  Periods.thu6: null,
  Periods.fri1: null,
  Periods.fri2: null,
  Periods.fri3: null,
  Periods.fri4: null,
  Periods.fri5: null,
  Periods.fri6: null,
  Periods.sat1: null,
  Periods.sat2: null,
  Periods.sat3: null,
  Periods.sat4: null,
  Periods.sat5: null,
  Periods.sat6: null,
};
